### ISSUE TITLE
无法设置，没有设置页面，禁用时不删除表

### ISSUE THREAD

**Issue by simonsmh** [Hanccc/Links-for-Material-Theme#1]
数据库是MySQL(mariadb)
PHP 7.0.12
如题
如何使用？

**Comment by hcrgm** [comment]
不会吧？我这正常，同mariadb和php7
设置页有的，在：/admin/extending.php?panel=Links%2Fmanage-links.php
至于不删表，那是为了下次启用不用重新设置嘛，目前大部分插件都是这么做的，删表也就一条语句的事

**Comment by simonsmh** [comment]
@hcrgm 找到了，设置居然藏在管理项。。
`至于不删表，那是为了下次启用不用重新设置`
你禁用再重新启用看看，这时启用会抛异常。。
